library:
  source-dirs: src
tests:
  stepik-haskell-course-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stepik-haskell-course
copyright: 2020 Author name here
maintainer: example@example.com
dependencies:
- directory
- split
- old-locale
- time >= 1.5
- base >= 4.7 && < 5
name: stepik-haskell-course
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/stepik-haskell-course
license: BSD3
executables:
  stepik-haskell-course-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stepik-haskell-course
description: Please see the README on GitHub at <https://github.com/githubuser/stepik-haskell-course#readme>
